export const EMPTY_STRING = "";

export const ACTIONS_REDUX = {
  SET_USER_LIST: "SET_USER_LIST",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_SELECTED_USER: "SET_SELECTED_USER",
  REMOVE_USER: "REMOVE_USER",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
};
